### ISSUE TITLE
greaterOrEqual ?

### ISSUE THREAD

**Issue by benavern** [mvrlin/nuxt-viewport#11]
Hi,  thank you for your work on this, I will be using it for sure.

However I miss something: 
I'm working on a mobile-first project and I'd like to align the css and js breakpoint names:

<details>
  <summary>
  My configuration
  </summary>

* in scss I use 
```scss
$breakpoints: (
    xs: 320px,
    sm: 768px,
    md: 1024px,
    lg: 1200px,
    xl: 1600px
);
```

* in nuxt I have
```js

    viewport: {
        breakpoints: {
            xs: 320,
            sm: 768,
            md: 1024,
            lg: 1200,
            xl: 1600,
        },

        defaultBreakpoints: {
            mobile: 'xs',
            tablet: 'sm',
            desktop: 'md',
        },

        fallbackBreakpoint: 'xs',
    },
``` 
</details>

---

<details>
  <summary>
  The issue I face
  </summary>

For exemple, when using `sm` breakpoint 

* in scss:
```scss 
@media (min-width: map-get($breakpoints, 'sm')) {
 // ...
}
```
* in vue:
```html
// 😱 I want the breakpoint to be at least "sm", so I have to use "xs" in the template!!!
<MyComponent v-if="$viewport.isGreaterThan('xs')" />
```
</details>

---

<details>
<summary>
My suggestions
</summary>

I would be cool to add a new method to make it more "'mobile-first friendly".

For exemple, `$viewport.isGreaterOrEquals('sm')` or `$viewport.isAtLeast('sm')`
</details>

**Comment by mvrlin** [comment]
@benavern 

Hey! Thanks ;)
You can use `$viewport.isLessThan('md')` if you want to render only for `xs` and `sm`

**Comment by benavern** [comment]
Yes but my goal here is to think the same way I think in scss. Not overriding for smaller but bigger screens.

the example for sm is the same for all the other breakpoints I have, I think it would be nice to have a `>=` feature additionally to the `>` feature that is too strict for my (and others I'm sure) use.

I'll try to make a PR tonight (in France) If I find time :)
