### ISSUE TITLE
Breaks on static build

### ISSUE THREAD

**Issue by mirko-kienle** [mvrlin/nuxt-viewport#2]
Hi, thanks for this module. Unfortunately it breaks for me on a static build:

```
TypeError: Cannot destructure property `headers` of 'undefined' or 'null'.
at viewport_server (node_modules/.cache/nuxt/viewport.server.js:8:0)
```

It looks like `ctx.ssrContext.req` isn't there in a static build.

This might be a solution, unfortunately I don't have time to open a PR and test it right now:

**plugin.server.js**
```js
export default async function (ctx, inject) {
  const options = <%= serialize(options) %>

  if (ctx.ssrContext.target === 'static') {
    ctx.beforeNuxtRender(({ nuxtState }) => {
      nuxtState.viewport = options.fallbackBreakpoint
    })

    return
  }
...
}
```

**Comment by mvrlin** [comment]
@mirko-kienle Hey! Thanks for the issue. Checkout the latest release, should be fixed now ☺️

**Comment by mirko-kienle** [comment]
Awesome @mvrlin, thanks so much! I didn't think I'd get this quick of a response so I already re-factored around the issue now, but what an amazing turnaround 🚀.

I'm closing this issue, good to know that the module will be ready next time I need it. 🙂
