### ISSUE TITLE
Breakpoints are merged with defaults

### ISSUE THREAD

**Issue by ronenteva** [mvrlin/nuxt-viewport#28]
It seems that the configured breakpoints are merged with the defaults instead of replacing them.

```
breakpoints: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      '2xl': 1536
    }
```

![image](https://user-images.githubusercontent.com/2454954/202576381-6cbfd054-8378-4af2-8b23-7f5807c24656.png)

**Comment by mvrlin** [comment]
> It seems that the configured breakpoints are merged with the defaults instead of replacing them.
> 
> 
> 
> ```
> 
> breakpoints: {
> 
>       xs: 320,
> 
>       sm: 640,
> 
>       md: 768,
> 
>       lg: 1024,
> 
>       xl: 1280,
> 
>       '2xl': 1536
> 
>     }
> 
> ```
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2454954/202576381-6cbfd054-8378-4af2-8b23-7f5807c24656.png)
> 
> 

😯 I'll take a look

**Comment by mvrlin** [comment]
@ronenteva https://www.npmjs.com/package/nuxt-viewport/v/2.0.2 fixed!

**Comment by mvrlin** [comment]
> @mvrlin this is not working with the latest released version, do you know something about it ?

Hi! Maybe that's because I used the `defaults` prop, i'll fix that soon. Thanks!

**Comment by norbertSG** [comment]
> > @mvrlin this is not working with the latest released version, do you know something about it ?
> 
> Hi! Maybe that's because I used the `defaults` prop, i'll fix that soon. Thanks!

When do you estimate to release the fix for this ?

**Comment by mvrlin** [comment]
@norbertSG already did that :) Checkout the latest release!
