### ISSUE TITLE
Hydration mismatch when layout exists

### ISSUE THREAD

**Issue by serialine** [mvrlin/nuxt-viewport#30]
### Reproduce

https://stackblitz.com/edit/github-bsckim?file=playground/pages/index.vue

### Description

When Nuxt layout exist
Server rendered "desktopWide"
but client unexpected rendered "mobile" (fallbackBreakpoint).

I don't know why 😅 

### Error

```
[Vue warn]: Hydration text content mismatch in <b>:
- Client: "mobile"
- Server: "desktopWide" 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/" routeProps= Object pageKey="/"  ... > 
  at <Anonymous > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default > 
  at <Anonymous key="default" name="default" hasTransition=false > 
  at <Anonymous > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by mvrlin** [comment]
@serialine Hello! That's happening because of the cookie rules, when you make a first request and you don't have any cookie set yet, the server will send a `Set-Cookie` header and because it has `SameSite=Strict` rule it doesn't allow to be set in the iframe.

**Comment by serialine** [comment]
> @serialine Hello! That's happening because of the cookie rules, when you make a first request and you don't have any cookie set yet, the server will send a `Set-Cookie` header and because it has `SameSite=Strict` rule it doesn't allow to be set in the iframe.

@mvrlin Thank you for answer
I understand that it happens because the cookie does not exist on the first request as you answered.
I've tried in localhost, checked set-cookie triggered. however, it's a bit strange that it only happens when the layout exists. If delete layout directory, not happens. 🤔

**Comment by serialine** [comment]
Anyway it doesn't seem like a bug in the module, so I'll close the issue! thank you.
