### ISSUE TITLE
Cookie set for all paths with the same name

### ISSUE THREAD

**Issue by ploca14** [mvrlin/nuxt-viewport#34]
# Description
The cookie is getting set for all paths with the same name, resulting in incorrect cookie values being parsed. When visiting the `/foo/bar` page, the parsed cookie value is `sm` instead of `lg`.

![image](https://user-images.githubusercontent.com/28987123/229080259-78e77bfe-39c8-4a62-b330-30ce58d5cc1b.png)

# Steps to Reproduce
Visit page `/` on mobile and then visit page `/foor/bar` on desktop. 

# Expected Behavior
The cookie value should be correctly parsed based on the path of the current page.

# Actual Behavior
The cookie from the `/` path is used instead of the `/foo/bar` page.

# Additional Information
Browser sends the cookie header in this format: `viewport=lg; viewport=sm` and should send them ordered by path length.
So the most specific path is always first and the least specific is always last.
See https://stackoverflow.com/questions/4056306/how-to-handle-multiple-cookies-with-the-same-name.
The Object.fromEntries function used to parse the cookie header always returns the last entry if the key is the same.
This leads to the least specific path's cookie always being used instead of the most specific path's cookie.

# Solution
One solution is to also set the cookie path when setting the cookie to `path=/`. That way all pages will use the same cookie.
(I don't see the reason why separate cookies for separate pages could be needed)

If separate cookies for specific pages are needed, one solution is to always use the first value instead of the last one by reversing the entry array when parsing the cookie. This counts on the browser to adhere to the RFC.

**Comment by mvrlin** [comment]
@ploca14 Hey! Thank you for your PR, totally missed the path. I'll publish the new version ASAP. ❤️
