### ISSUE TITLE
Typescript VSCode error

### ISSUE THREAD

**Issue by dtrinh100** [mvrlin/nuxt-viewport#37]
When using the `viewport` property in `nuxt.config.ts`, I am seeing this error:

`Object literal may only specify known properties, and 'viewport' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.`

My nuxt.config.ts file:
```
export default defineNuxtConfig({
  modules: [
    "nuxt-viewport",
  ],
  viewport: {
    // breakpoints set
  },

});
```

I am using Nuxt 3.5.1. Is there a way to get rid of the error? It also looks like the module is not being auto imported.

**Comment by mvrlin** [comment]
@dtrinh100 Hey, what's the version of `nuxt-viewport` are you using?
