### ISSUE TITLE
Max-width media query

### ISSUE THREAD

**Issue by rbrt457** [mvrlin/nuxt-viewport#39]
Hi! I suggest changing the max-width of media query from -1 to -0.02. I noticed that some devices with a screen resolution increased by 125% do not respond to the 767px breakpoint because they have a width of 767.2px. Therefore, I think it would be better to make such a change.
![image](https://github.com/mvrlin/nuxt-viewport/assets/64192482/32c85fd3-a9a1-417d-9b41-87cd6b4b3a97)

**Comment by mvrlin** [comment]
> Hi! I suggest changing the max-width of media query from -1 to -0.02. I noticed that some devices with a screen resolution increased by 125% do not respond to the 767px breakpoint because they have a width of 767.2px. Therefore, I think it would be better to make such a change.
> 
> ![image](https://github.com/mvrlin/nuxt-viewport/assets/64192482/32c85fd3-a9a1-417d-9b41-87cd6b4b3a97)
> 
> 

Hi, I didn't thought that it's actually possible to have a float width, I'll check that out

**Comment by mvrlin** [comment]
@rbrt457 напиши мне в Телеграм https://t.me/mvrlin
