### ISSUE TITLE
Vitest

### ISSUE THREAD

**Issue by zarskilukasz** [mvrlin/nuxt-viewport#41]
Hi, i want to test the component using Nuxt-Viewport. I'm receiving an error ... 
![Zrzut ekranu 2023-06-19 o 14 20 24](https://github.com/mvrlin/nuxt-viewport/assets/14441265/cb92dae3-9381-45ae-a750-0bbf5bbb27a2)
How can I mock or import it?

**Comment by mvrlin** [comment]
@zarskilukasz Hi! Can you provide your vitest config?

**Comment by zarskilukasz** [comment]
`import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'
import path from 'path'

export default defineConfig({
  plugins: [vue()],
  test: {
    globals: true,
    environment: 'happy-dom',
    include: ['**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    exclude: [
      'node_modules',
      'coverage',
      'storybook-static',
      '.output',
      'assets',
      'public',
      '.nuxt'
    ],
    coverage: {
      provider: 'c8'
    }
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './')
    }
  }
})`

**Comment by mvrlin** [comment]
@zarskilukasz did you tried using this https://github.com/danielroe/nuxt-vitest?

**Comment by zarskilukasz** [comment]
@mvrlin thanks it works
