### ISSUE TITLE
Tweaks

### ISSUE THREAD

**Issue by or2e** [mvrlin/nuxt-viewport#46]
When using your module (thank you!) we ran into a few problems
We will describe them in more detail later, for now a note so you don't forget them

TODO:
- [`useCookie`](https://nuxt.com/docs/api/composables/use-cookie) - handy tool out of the box + `BroadcastChannel`
- ~~ua-parser-js~~ -> [`bowser`](https://github.com/lancedikson/bowser) <details>
  <summary>Stopped detecting many cases, such as the most common desktop.</summary>
  
  ![image](https://github.com/mvrlin/nuxt-viewport/assets/33551334/d23a13bb-62c4-482a-8a30-622fe2782106)
</details>

- ~~app:mounted~~ -> [`app:suspense:resolve`](https://nuxt.com/docs/api/advanced/hooks#app-hooks-runtime) - case where we want to make a dynamic layout
a hydration error occurs in several situations
```
// app.vue
NuxtLayout(:name='isMobile ? "mobile" : "desktop"')
```

**Comment by mvrlin** [comment]
Hi! Thank you for the issue. I'm waiting for details.

**Comment by mvrlin** [comment]
Thanks for your contribution! Please check out https://www.npmjs.com/package/nuxt-viewport/v/2.1.0
