### ISSUE TITLE
Error on nuxt 3.9.3

### ISSUE THREAD

**Issue by aastrum** [mvrlin/nuxt-viewport#51]
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/cookie/index.js?v=bde41b3e' does not provide an export named 'serialize' (at manager.mjs?v=bde41b3e:1:10)

**Comment by mvrlin** [comment]
@aastrum Hi! Please checkout the latest release https://www.npmjs.com/package/nuxt-viewport/v/2.1.2

**Comment by aastrum** [comment]
> @aastrum Hi! Please checkout the latest release https://www.npmjs.com/package/nuxt-viewport/v/2.1.2

It works well. Thanks a lot!

**Comment by or2e** [comment]
@mvrlin hey )

I want to point out something.
Nuxt has a built-in comosable [useCookie ](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/cookie.ts)that uses [cookie-es](https://github.com/unjs/cookie-es) under the hood.
