### ISSUE TITLE
Add CloudFront Support

### ISSUE THREAD

**Issue by zweeen** [mvrlin/nuxt-viewport#52]
Hi @mvrlin 🙂,

[nuxt-viewport](https://github.com/mvrlin/nuxt-viewport) is very amazing thanks to you.
I am wondering if it's possible to add cloudfront support.

[nuxt-viewport](https://github.com/mvrlin/nuxt-viewport) is based on [bowser](https://github.com/bowser-js/bowser) but bowser doesn't know how to detect cloudfront `user-agent` and fallback to default breakpoint. If a request is sent to a application within a AWS server, cloudfront will override the real user-agent by setting it's own user-agents:

- CloudFront-Is-Mobile-Viewer
- CloudFront-Is-Tablet-Viewer
- CloudFront-Is-Desktop-Viewer
- CloudFront-Is-Ios-Viewer
- CloudFront-Is-Android-Viewer

I think that this feature will be very appreciated, because a lot of application are deployed with AWS.

We can rely on what [nuxt device ](https://github.com/nuxt-modules/device?tab=readme-ov-file#cloudfront-support)(a nuxt module device detection) do maybe.

**Comment by mvrlin** [comment]
Hey! Sure, I'll take a look, but I don't have any idea how to test it.

**Comment by zweeen** [comment]
@mvrlin I think that we can config Nuxt to pass a specific user-agent. 

If you want, before realeasing you can create a temporary branch. Like that we will be able to test it.
I have a AWS server I can test it in my side also.

**Comment by mvrlin** [comment]
@zweeen Great! I made the branch for you https://github.com/mvrlin/nuxt-viewport/tree/cloudflare
You can test it 😊

**Comment by zweeen** [comment]
@mvrlin, oh dude, thank you a lot really 😃,

I will test it today, I will be back to you on this just Asap.

**Comment by zweeen** [comment]
Heya @mvrlin ,

Sorry for my late response. I couldn't test it yesterday. Now I tried your branch locally and it's seems to work very well 👍🏼 .
I think you can release another version 🙂 .

**Comment by zweeen** [comment]
Heya @mvrlin ,

Do you think it will be possible to release a new version today ? I will be able to test it and confirm that in a real AWS server it's work 🙂 (within my company).

**Comment by mvrlin** [comment]
@zweeen Sure, i'll release in a few minutes

**Comment by mvrlin** [comment]
@zweeen Done. Please checkout https://www.npmjs.com/package/nuxt-viewport/v/2.1.4

**Comment by zweeen** [comment]
@mvrlin Thanks a lot 😃 you rock

**Comment by zweeen** [comment]
https://www.npmjs.com/package/nuxt-viewport/v/2.1.4 🥇 work like a charm, tested with a real AWS server

Thank you again for your reactivity @mvrlin.

I close the issue
