### ISSUE TITLE
Viewport makes 2 changes

### ISSUE THREAD

**Issue by alederzz** [mvrlin/nuxt-viewport#54]
I have an image (130kb) that should only load and display on desktop

I also have defined fallbackBreakpoint: 'md'

// but this also loads in the background on mobile
```
<div class="banner__top-desktop" v-if="viewport.isGreaterThan('md')">
  <NuxtImg :src="__desktopImage__" width="1140" height="640"  />
</div>
```

I have noticed, this is because when it starts it takes the fallback value as a base and then updates it to the one obtained by the mediaquery.

md -> xs

**Comment by mvrlin** [comment]
Hi, @alederzz 
Can you show me `nuxt.config.ts` viewport options and what's your Nuxt version?

**Comment by alederzz** [comment]
Hi, @mvrlin 

nuxt version 3.8

// https://nuxt.com/docs/api/configuration/nuxt-config
```
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      gtm: {
        ....
      },
    }
  },
  routeRules: {
    '/**': { swr: 120 },
    '/api/post/**': { swr: 60 },
    '/api/author/**': { swr: 60 * 60 * 3 },
    '/wp-admin/**': { redirect: '/' },
  },
  css: ['~/assets/css/main.css'],
  postcss: {
    plugins: {
      'tailwindcss/nesting': {},
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  build: {
    transpile: ['tslib'],
  },
  modules: [
    '@nuxtjs/google-fonts',
    '@nuxt/image',
    '@pinia/nuxt',
    '@stefanobartoletti/nuxt-social-share',
    'nuxt-viewport',
    '@zadigetvoltaire/nuxt-gtm',
  ],
  pinia: {
    storesDirs: ['./stores/**'],
  },
  googleFonts: {
    families: {
      Roboto: [400, 700],
      Poppins: [400, 500, 700, 800],
    },
    display: 'swap',
  },
  image: {
     ....
  },
  viewport: {
    breakpoints: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      '2xl': 1536,
    },

    defaultBreakpoints: {
      desktop: 'lg',
      mobile: 'xs',
      tablet: 'md',
    },

    fallbackBreakpoint: 'md'
  },
  devtools: {
    enabled: true,
  },
  experimental: { componentIslands: true },
})
```

**Comment by alederzz** [comment]
I noticed this change persists when SWR is enabled

**Comment by mvrlin** [comment]
> I noticed this change persists when SWR is enabled

Can you please make a StackBlitz or CodeSandbox example?

**Comment by alederzz** [comment]
> > I noticed this change persists when SWR is enabled
> 
> Can you please make a StackBlitz or CodeSandbox example?

Of course.

https://stackblitz.com/edit/github-orw7x1?file=nuxt.config.ts

**Comment by alederzz** [comment]
Would this be a NUXT problem?

**Comment by mvrlin** [comment]
@alederzz Hey! Sorry for late response, I'm kinda busy right now at my job. I'll try to take a look until the end of this week.

**Comment by mvrlin** [comment]
@alederzz Due to it's SWR caching mechanism, it is not possible to not render twice. Maybe consider some alternatives, you can take a look here https://blog.risingstack.com/nuxt-3-rendering-modes/
