### ISSUE TITLE
Feat: option to use max media queries instead of min-width

### ISSUE THREAD

**Issue by meirroth** [mvrlin/nuxt-viewport#61]
Hi, I'm currently working on a project that uses `max-width` media queries, which unfortunately makes this module incompatible with our setup.

For instance, in our project, `xs` corresponds to `max-width: 600px`. However, when using this module with the following configuration:
```
  viewport: {
    breakpoints: {
      xs: 600,
      sm: 768,
      md: 1024,
      lg: 1280,
      xl: 1536,
    },

    defaultBreakpoints: {
      desktop: 'lg',
      mobile: 'xs',
      tablet: 'md',
    },

    fallbackBreakpoint: 'lg',
  },
```

The xs breakpoint translates to `(min-width: 1px) and (max-width: 767px)`, which doesn't align with our project's requirements.

This behavior seems to be rooted in the following lines of code: 
https://github.com/mvrlin/nuxt-viewport/blob/4d20486f9a585d6ece7b7d2665f14a6f99e6ff93/src/runtime/manager.ts#L70-L74

It would be immensely beneficial if there was an option to switch between min-width and max-width media queries, allowing for greater flexibility and compatibility with different project requirements.

I am willing to contribute by opening a PR to implement this feature if it aligns with the project's direction.

Thank you,
Meir

**Comment by mvrlin** [comment]
@meirroth Hi! Sure, you can open the PR. There must be such a need, I'll review it as soon as possible. At my projects, I'm mostly sticking with **mobile-first** approach.

**Comment by meirroth** [comment]
@mvrlin What should we call this new option `max: false`, `mobileFirst: true`, or?

**Comment by mvrlin** [comment]
@meirroth 

I found this https://developer.mozilla.org/en-US/docs/Web/CSS/@media/width
We can add an option like so:
```typescript
feature: 'minWidth' | 'maxWidth'
```

With that in mind I came up with an idea to use feature when needed like so:
```typescript
// Returns viewport with feature from options.
const viewport = useViewport()
// Returns the same viewport, but with maxWidth feature.
const viewportMax = useViewport().withFeature('maxWidth')
```

```vue
<div v-if="$viewport.withFeature('maxWidth').isLessThan('md')">Mobile Only</div>
```

What do you think?

**Comment by meirroth** [comment]
@mvrlin Ok sounds good. I'd be willing to open a PR if you want. Are we set on feature: 'minWidth' | 'maxWidth'?

**Comment by mvrlin** [comment]
@meirroth Sure I want. Let's do an option property `feature` with values `'minWidth' | 'maxWidth'` and make `minWidth` as default for convenience

**Comment by meirroth** [comment]
@mvrlin Done
