### ISSUE TITLE
Question about the cookie

### ISSUE THREAD

**Issue by meirroth** [mvrlin/nuxt-viewport#63]
Hi,
Can you please explain the benefit of having the viewport cookie if we can assume we got the userAgent? Is it because userAgent is not always accurate and can cause hydration mismatch without the cookie?
Thank you,
Meir

**Comment by mvrlin** [comment]
Hi! Yes and to use the same breakpoint on refresh.

**Comment by meirroth** [comment]
Got it. Thank you!

**Comment by alessiochiffi** [comment]
hi, is there a way to set the cookie to HTTPOnly flag? Thanks

**Comment by mvrlin** [comment]
> hi, is there a way to set the cookie to HTTPOnly flag? Thanks

Hey! Unfortunately not, why do you need that?
