### ISSUE TITLE
Add nuxt-viewport to nuxt.config.ts modules, then typescript not working

### ISSUE THREAD

**Issue by boss006133** [mvrlin/nuxt-viewport#71]
[test-typescript.zip](https://github.com/user-attachments/files/16690545/test-typescript.zip)
I just create a new nuxt3 app, and add only one module(nuxt-viewport), then I auto import a const from nuxt.config.ts like the code below

nuxt.config.ts
```
export default defineNuxtConfig({
  compatibilityDate: "2024-04-03",
  devtools: { enabled: true },
  modules: ["nuxt-viewport"],
  imports: {
    dirs: ["constants/others"],
  },
  typescript: {
    typeCheck: true,
  },
})
```
![image](https://github.com/user-attachments/assets/5d3b5034-ae84-43e2-bad9-fc2bb0f62c47)

and make the typescript not working

![image](https://github.com/user-attachments/assets/2ffac5eb-69f3-4f39-ac33-8233fc1f8283)

package.json
```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "sass": "1.77.6",
    "sass-loader": "^13.3.2",
    "typescript": "^5.5.4",
    "vue-tsc": "^2.0.29"
  },
  "dependencies": {
    "nuxt": "^3.12.4",
    "nuxt-viewport": "^2.1.5",
    "vue": "latest"
  }
}
```

**Comment by mvrlin** [comment]
Hi! I don't think it's a `nuxt-viewport` issue. Update your `tsconfig.json`:
```json
"include": [ // 納入 .vue 文件
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "env.d.ts",
    ".nuxt/nuxt.d.ts",
    "constants/**/*.ts" // <-- here
  ],
```

**Comment by boss006133** [comment]
@mvrlin vue-tsc now is 0 errors, but typescript intellisense still not working on both `CLASSNAME_DS_V_MENU` and `useNuxtApp()`
![image](https://github.com/user-attachments/assets/7634fdc0-9b26-4e1f-b929-7a6300013192)
![image](https://github.com/user-attachments/assets/218200a4-4e2c-4169-bc51-23019a2197c9)

my tsconfig.json
```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "target": "ES2023",
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowJs": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "noImplicitAny": false,
  },
  "include": [ // 納入 .vue 文件
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "env.d.ts",
    ".nuxt/nuxt.d.ts",
    "constants/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Comment by boss006133** [comment]
If I remove `"nuxt-viewport"` from nuxt.config.ts modules, then typescript intellisense works fine
